### ISSUE TITLE
git-chglog deletes manual non-semantic changelog entries

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#119]
On the release of `v0.4.1` several problems with changelog and the release process appeared:

- Main branch is protected, the documented `TAG=v0.4.1 make tag` will need a PR, and to push the tag separately.
- `git-chglog` doesn't work nicely with manually edited changelogs, such as `v0.4.0`. It doesn't allow to skip versions, and it adds a footer with a link for the history bracket. We could manually concatenate the different parts of the changelog, but this process would change every time there's a new versio entry that was manually edited (this may be often, as we are not yet following full semantic commits).
- The recommended upstream solution is to make the changes on the changelog.tmpl: https://github.com/git-chglog/git-chglog/issues/55.

#### Workaround

For `v0.4.1`, instead of `TAG=v0.4.1 make tag`, I did:
```console
git-chglog --next-tag v0.4.1 -o CHANGELOG.md
<edit CHANGELOG.md to reset unwanted changes to old versions, but add the changes relevant to new version>
git commit -m 'Update CHANGELOG.md'
<open PR, merge PR>
git tag -a v0.4.1  -m "v0.4.1" -s
git push origin v0.4.1
<let GH actions create the release>
```

See the PR for that release: https://github.com/kubewarden/kubewarden-controller/pull/118.

**Comment by ereslibre** [comment]
First of all, I'm perfectly fine improving the process, I'm not opposing to any kind of change, all is good.

> git-chglog doesn't work nicely with manually edited changelogs

Yeah, changelogs are always automatically generated and should not be manually modified. Release notes can though, since they serve differennt purposes.

Also, but this is more of a personal opinion, I think is good to not skip versions, if the tag is there it makes sense to include in the changelog, even if it was a faulty release.

> it adds a footer with a link for the history bracket

What do you mean with this?

Regarding skipping versions, we can always either leave the tag alone, and include it in our changelog, after all is part of the history, or delete the tag altogether if we don't want people to be able to use that tag at all because is faulty or similar.

**Comment by viccuad** [comment]
> Yeah, changelogs are always automatically generated and should not be manually modified. Release notes can though, since they serve different purposes.

Indeed. Thing is, we aren't yet following www.conventionalcommits.org as `git-chglog` parses, so our changelogs are empty or worse, misleading. Maybe it's a culture difference since I'm used to other changelog workflows where changelogs are manually edited together with the changes (eg: debian/changelog in .deb).

Good point about the release notes. To be fair, it's not like we are using them much either, and I dislike that one needs to fill them manually on Github, and aren't part of history.

> Regarding skipping versions, we can always either leave the tag alone, and include it in our changelog, after all is part of the history, or delete the tag altogether if we don't want people to be able to use that tag at all because is faulty or similar.

It's just that `git-chglog` doesn't allow to just compile the latest tag, without touching the rest. With the footer, I mean the diff links at the end https://github.com/kubewarden/kubewarden-controller/blob/b8191434b25ec6379d57420e347606c1a286ccfc/CHANGELOG.md?plain=1#L147-L163.
