### ISSUE TITLE
Unable to remove unschedulable clusteradmissionpolicy

### ISSUE THREAD

**Issue by chrisns** [kubewarden/kubewarden-controller#130]
👋 
```
$ kubectl apply -f - <<EOF
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: privileged-pods
spec:
  policyServer: typo
  module: registry://ghcr.io/kubewarden/policies/pod-privileged:v0.1.9
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: false
EOF

$ kubectl get ClusterAdmissionPolicy
NAME               POLICY SERVER                    MUTATING   STATUS
privileged-pods    typo                             false      unschedulable

$kubectl delete clusteradmissionpolicies.policies.kubewarden.io privileged-pods
clusteradmissionpolicy.policies.kubewarden.io "privileged-pods" deleted
***hangs***
^C
$ kubectl get ClusterAdmissionPolicy
NAME               POLICY SERVER                    MUTATING   STATUS
privileged-pods    typo                             false      unschedulable

```
only way to remove is apparently to edit the `ClusterAdmissionPolicy` and remove the `kubewarden` `finalizer` then it disappears

Because the `policyServer` field is immutable,  the only way to fix a typo like this is to remove the finalizer and try again 😢

**Comment by viccuad** [comment]
Thanks for reporting this! Yes, indeed, the UX here can be fixed.

On the implementation side, this is happening because policies get reconciled as part of the PolicyServer loop.
We can defer adding the Finalizer to when the policy is scheduled in a PolicyServer (so in this case a badly configured ClusterAdmissionPolicy will not have a finalizer yet). Another option, suggested by @raulcabello, is to remove the finalizer [at this point](https://github.com/kubewarden/kubewarden-controller/blob/main/controllers/policies/policyserver_controller.go#L177-L183) in the watch, for now.
