### ISSUE TITLE
Refresh artifacthub-pkg.yml in policies by using automation

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#325]
The Kubewarden policies published in the Artifacthub have wrong dates for their version. For example the [allow-privilege-escalation-psp](https://artifacthub.io/packages/kubewarden/allow-privilege-escalation-psp/allow-privilege-escalation-psp) and [environment-variable-policy](https://artifacthub.io/packages/kubewarden/environment-variable-policy/environment-variable-policy) show `19 Jul, 2022` as the last release date. But this is a wrong information. 

As @viccuad pointed out, this info seems to come from the [artifacthub-pkg.yml](https://github.com/kubewarden/environment-variable-policy/blob/main/artifacthub-pkg.yml#L5) file. We should fix this in all our policies. Furthermore, I believe we should have a CI to automatically update this field for us every release.

**Comment by flavio** [comment]
This filed is coming from the policy template, this should be set only once: when the policy has been created for the 1st time. Hence, I don't think we need to do any automation around that.

Instead, I propose the following actions:

* rust template: update our cargo-generator to compute the value of `createdAt` file at execution time
* go, opa, gatekeeper templates: add a `TODO` comment over there, stating the user must change that. Unfortunately there's nothing else we can do over there

**Comment by jvanz** [comment]
> This filed is coming from the policy template, this should be set only once: when the policy has been created for the 1st time. Hence, I don't think we need to do any automation around that.

I don't think so. If you see the [RSS file](https://artifacthub.io/api/v1/packages/kubewarden/allow-privilege-escalation-psp/allow-privilege-escalation-psp/feed/rss). The date is used as the version publication date. If this date should be the policy creation date, we have a bug in the artifacthub.

**Comment by tegioz** [comment]
Hi @jvanz

Yes, the `createdAt` field should be updated for each release.

**Comment by jvanz** [comment]
> Hi @jvanz
> 
> Yes, the `createdAt` field should be updated for each release.

Ok! Thanks for the quick feedback!

**Comment by geeksambhu** [comment]
I am working on this.

**Comment by flavio** [comment]
> I am working on this.

@geeksambhu thanks for your help! How do you plan to fix that, are you going to fix all the entries manually or provide some automation?

**Comment by viccuad** [comment]
@geeksambhu I'm sorry, made a mistake in judgement and communication, and this card is closer to completion than I thought.

Thing is, admittedly, this is a somewhat simple card to tackle, but needs quite the background knowledge on Kubewarden, our repos, and artifacthub. So I totally understand if you would prefer to change to a different task.

Let me lay out what is needed for this card to progress:

---

In the beginning, this card was about going through the list of policies that we own in https://github.com/topics/kubewarden-policy, and editing `artifacthub-pkg.yml`, preferably with a new CI job, so they are up to date.

This turned out to be a bit more extensive than thought, and it spawned https://github.com/kubewarden/kubewarden-controller/issues/389. We have progressed on that card, which means we have added the needed features to `kwctl` (our own cli utility, released as 1.6.0-rc2 and soon to be released as 1.6.0), and bumped our github.com/kubewarden/github-actions  to a v2 that uses those `kwctl` features.

This means that was is left over to be done is, to iterate through the [~29 policies](https://github.com/topics/kubewarden-policy) that we have and are under the kubewarden org (not community ones):
1. Make sure that they have a new `make artifacthub-pkg.yml` target in their Makefile so that our github-actions@v2 can call it.
1. Bump their usage of our github-actions to github-actions@v2
1. Update `metadata.yml` according to errors shown in `make artifacthub-pkg.yml`, until a good `artifacthub-pkg.yml` is created.
1. Commit the changes to `metadata.yml` and `artifacthub-pkg.yml`.
1. Bump policy version and release it.

An example of a PR for a policy is: https://github.com/kubewarden/allowed-fsgroups-psp-policy/pull/25.

**Comment by viccuad** [comment]
@geeksambhu , if you select this card, you can tackle one or several policies, and we can think about different tasks to not fall into monotony.

Current progress so far:

Rust policies:
- [ ] allowed-fsgroups-psp-policy
      https://github.com/kubewarden/allowed-fsgroups-psp-policy/pull/25
- [ ] allowed-proc-mount-types-psp-policy
- [ ] allow-privilege-escalation-psp-policy
- [ ] apparmor-psp-policy
- [ ] capabilities-psp-policy
- [ ] deprecated-api-versions-policy
- disallow-default-namespace-policy (community policy, done as part of https://github.com/kubewarden/kubewarden-controller/issues/418)
- [ ] echo
- [ ] environment-variable-policy
- [ ] env-variable-secrets-scanner-policy
- [ ] flexvolume-drivers-psp-policy
- [ ] host-namespaces-psp-policy
- probes-policy (community policy, done as part of https://github.com/kubewarden/kubewarden-controller/issues/418)
- [ ] pod-privileged-policy
- [ ] readonly-root-filesystem-psp-policy
- [ ] seccomp-psp-policy
- [ ] selinux-psp-policy
- [ ] sleeping-policy
- [ ] trusted-repos-policy
- [ ] user-group-psp-policy
- [ ] verify-image-signatures
- [ ] volumeMounts-policy

Go policies:
- [ ] hostpaths-psp-policy
- [ ] ingress-policy
- [ ] safe-annotations-policy
- [ ] safe-labels-policy
- [ ] sysctl-psp-policy
- [ ] volumes-psp-policy

Rego policies:
- [ ] disallow-service-loadbalancer-policy
- [ ] disallow-service-nodeport-policy

Swift:
- [ ] pod-runtime-class-policy

**Comment by viccuad** [comment]
just note, if you are working on a PR locally (doing a `make annotated-policy.wasm`, that triggers a `make artifacthub-pkg.yml`), you need `kwctl` [version 1.6.0-rc2](https://github.com/kubewarden/kwctl/releases/tag/v1.6.0-rc2), which has the `kwctl scaffold artifacthub` functionality. This same version is used in the github-actions, [see here](https://github.com/kubewarden/github-actions/blob/main/kwctl-installer/action.yaml#L10).

**Comment by viccuad** [comment]
@geeksambhu , I will reserve you the first 5 of the list, to see how we are progressing with it:
allowed-proc-mount-types-psp-policy
allow-privilege-escalation-psp-policy
apparmor-psp-policy
capabilities-psp-policy
deprecated-api-versions-policy

**Comment by geeksambhu** [comment]
Hi @viccuad , I picked up `allowed-proc-mount-types-psp-policy` in this [PR](https://github.com/kubewarden/allowed-proc-mount-types-psp-policy/pull/24). I am expecting your feedback. I am working on this `allow-privilege-escalation-psp-policy` next

**Comment by flavio** [comment]
Everything is done, except for the pod-runtime policy. This policy is written using Swift, but we want to rewrite that using Rust/Go as tracked by https://github.com/kubewarden/pod-runtime-class-policy/issues/15
We are going to handle the artifact scaffold as part of the policy rewrite
