### ISSUE TITLE
Unable to uninstall kubewarden: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kubewarden-controller#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am not able to uninstall kubewarden. This issue started 5 days ago, [this](https://github.com/kubewarden/kubewarden-controller/actions/runs/3972280009) is the first failed ci run.

To reproduce: install kubewarden with steps described on kubewarden.io (Get Started) on k3d cluster.

```
~ helm uninstall -n kubewarden kubewarden-controller kubewarden-crds kubewarden-defaults
Error: timed out waiting for the condition

~ kubectl get pods -n kubewarden
kubewarden     kubewarden-controller-zzbbq                0/1     CreateContainerConfigError

~ k describe pod -n kubewarden kubewarden-controller-zzbbq
kubelet            Successfully pulled image "ghcr.io/kubewarden/kubectl:v1.23.3" in 2.902940184s
kubelet            Error: container has runAsNonRoot and image will run as root (pod: "kubewarden-controller-zzbbq_kubewarden(a328c3c1-37b2-4e54-bf86-a9c69a396817)", container: pre-delete-job)
kubelet            Container image "ghcr.io/kubewarden/kubectl:v1.23.3" already present on machine
```

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by viccuad** [comment]
This started happening with: https://github.com/kubewarden/helm-charts/pull/187

The kubectl image we use is built from here https://github.com/kubewarden/rancher-kubectl-builder
which is consuming https://github.com/rancher/kubectl.
Our last build+sign of rancher/kubectl is 1.23.3, which is indeed run as root: https://github.com/rancher/kubectl/blob/v1.23.3/Dockerfile

rancher/kubectl has a newer tag, 1.23.7, which doesn't run as root: https://github.com/rancher/kubectl/blob/v1.23.7/Dockerfile#L16

Building + signing a new image from 1.23.7, and consuming it, will solve this issue.
The current build job fails for arm64 and succeeds for amd64: https://github.com/kubewarden/rancher-kubectl-builder/actions/runs/3725174781/jobs/6317815092.
I will start looking it it, or think about source our kubectl image from elsewhere, as rancher/kubectl is not particularly up-to-date either.

Also, we should have catched this before release, with an uninstall test.

**Comment by viccuad** [comment]
This is the issue about or build failure for kubewarden/kubectl:v1.23.7: https://github.com/kubewarden/rancher-kubectl-builder/issues/5

**Comment by viccuad** [comment]
Retriggered the rancher-kubectl-builder job, it build both the arm64 and amd64 tags and failed on creating the multiarch final tag: https://github.com/kubewarden/rancher-kubectl-builder/actions/runs/4014941516/jobs/6896075367

In contrast with [`v1.23.3-arm64`](https://github.com/orgs/kubewarden/packages/container/kubectl/23962207?tag=v1.23.3-arm64), `v1.23.3-amd64`, that only contain 1 arch layer each, the new `v1.23.7-arm64` and `v1.23.7-amd64` contain 2: their arch and an "unkown one".

I believe deleting tags `v1.23.7-arm64` and `v1.23.7-amd64` from https://github.com/kubewarden/rancher-kubectl-builder/pkgs/container/kubectl will make the build+sign job succeed.

**Comment by viccuad** [comment]
1. The `docker/build-push-action` doesn't seem to support a staged approach to build multiarchs, it
wants to do `platforms: linux/amd64, linux/arm64` at once. But we can't
do that, we need to change the build-arg `ARCH`, to consume the correct
kubectl from the correct arch.
The GHA creates tags whose manifest contain `linux/amd64` and
`unknown/unknown`. Hence being a manifest list, hence not being able to
amend the manifests later on into a `:v1.23.7` tag that contains both
arch layers..

2. The [bci-base:15.4.27.14.29](https://github.com/rancher/kubectl/blob/master/Dockerfile#L1) used just for downloading kubectl in the first stage of Dockerfile, well, doesn't have an arm64 layer.. So then our arm64 layer fails of course.

For 1, moved to call `docker` directly instead of using the GHA.
For 2, we need a new bump + tag upstream.
Current WIP on our side is at:
https://github.com/viccuad/rancher-kubectl-builder main branch
and the [action runs](https://github.com/viccuad/rancher-kubectl-builder/actions/workflows/build.yml).

**Comment by viccuad** [comment]
As a workaround, I suggest we fork `rancher/kubectl` for now, patch it consuming a different bci-base, and build our `kubewarden/kubectl` from there. Or we build our kubectl image without consuming `rancher/kubectl` (but then, we forego the automatic version bumps that seem to be coming with [rancher/kubectl/pull/45](https://togithub.com/rancher/kubectl/pull/45)).

**Comment by viccuad** [comment]
Thinking it through, I prefer to [consume the sigstore-signed releases of kubectl](https://kubernetes.io/blog/2022/12/12/kubernetes-release-artifact-signing/), and building the image FROM Scratch ourselves.

**Comment by viccuad** [comment]
Fixed with the release of kubewarden-controller 1.4.1.

**Comment by kravciak** [comment]
Tests pass again, thanks! https://github.com/kubewarden/kubewarden-controller/actions/runs/4026130069/jobs/6920301830
