### ISSUE TITLE
Ship Policy Reporter as part of our helm charts

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#498]
We would like to ship Policy Reporter as part of our helm charts to provide a better story around the audit scanner.

Things to understand:

* Do we need all the components of Policy Reporter?
* How can we make the deployment of Policy Reporter as easy as possible when deploying the Kubewarden stack?
* How would that fit with Kubewarden UI (in terms of the deployment story)?

**Comment by jvanz** [comment]
Okay, just a quick first feedback. As far as I can see, we need only two components of the policy report. The core one (the policy reporter itself) and the UI. For that, we can use the default policy reporter Helm chart and set a flag enabling the UI. I've tested an approach where we add the helm chart as a sub chart of the controller chart. This is the diff necessary for that:

```diff
diff --git a/charts/kubewarden-controller/Chart.yaml b/charts/kubewarden-controller/Chart.yaml
index d2df448..4c3a9be 100644
--- a/charts/kubewarden-controller/Chart.yaml
+++ b/charts/kubewarden-controller/Chart.yaml
@@ -44,3 +44,7 @@ annotations:
   # Valid values for the following annotation include: `cluster-tool`, `app` or `cluster-template`
   # See the Cluster Tools section to learn more about when to set this value to `cluster-tool`.
   catalog.cattle.io/type: cluster-tool
+dependencies:
+  - name: policy-reporter
+    version: 2.19.4
+    repository: https://kyverno.github.io/policy-reporter
diff --git a/charts/kubewarden-controller/chart-values.yaml b/charts/kubewarden-controller/chart-values.yaml
index b224288..d773c9a 100644
--- a/charts/kubewarden-controller/chart-values.yaml
+++ b/charts/kubewarden-controller/chart-values.yaml
@@ -110,3 +110,8 @@ auditScanner:
   containerRestartPolicy: Never
   # Additional namespaces that the audit scanner will not scan:
   skipAdditionalNamespaces: []
+
+policy-reporter:
+  ui:
+    enabled: true
+
diff --git a/charts/kubewarden-controller/values.yaml b/charts/kubewarden-controller/values.yaml
index c551ba0..b3a71b7 100644
--- a/charts/kubewarden-controller/values.yaml
+++ b/charts/kubewarden-controller/values.yaml
@@ -146,3 +146,8 @@ auditScanner:
   containerRestartPolicy: Never
   # Additional namespaces that the audit scanner will not scan:
   skipAdditionalNamespaces: []
+
+policy-reporter:
+  ui:
+    enabled: true
+
```

With this diff, I could install the policy reported and its UI installing the `kubewarden-controller` Helm chart command. It's seems quite easy to install everything in a single command. I'm not saying this is final solution. But it's interesting to see how it works smoothly in this example with NO further configurations. Furthermore, I need to validate how it works from Helm charts from repositories.  Because I've tested using my local helm chart version.

**Comment by flavio** [comment]
This looks clean, how is this going to work with airgap environments?

**Comment by jvanz** [comment]
> This looks clean, how is this going to work with airgap environments?

Good question. I'll validate that together with other tests that I have in my to do list.
