### ISSUE TITLE
Rewrite Webhook tests as unit tests

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#579]
Currently the webhook tests are written as integration tests, but we think they could be rewritten as unit tests. Integration tests are more expensive than unit tests.

## Acceptance criteria

* [x] Investigate if the webhook tests can be rewritten as unit tests
* [ ] Rewrite the webhook tests as unit tests

**Comment by fabriziosestito** [comment]
In the Makefile we call `go test` twice at line: https://github.com/kubewarden/kubewarden-controller/pull/576#discussion_r1398185754

This is needed since we have different envtest configuration, otherwise the real cluster tests will not show logs in the console for some reason. 
Once this PR is done we can remove the command related to webhooks integration tests.

**Comment by jvanz** [comment]
Just giving a feedback about the first acceptance criteria. I was reading the code of the `pkg/apis/policies/v1/webhook_suite_test.go` file. In summary, the [tests](https://github.com/kubewarden/kubewarden-controller/blob/0e5959e3f2a8395991470a104ac0f5f543a934ee/pkg/apis/policies/v1/webhook_suite_test.go#L301) are checking if the validations performed in the [`validateRulesField`](https://github.com/kubewarden/kubewarden-controller/blob/0e5959e3f2a8395991470a104ac0f5f543a934ee/pkg/apis/policies/v1/clusteradmissionpolicy_webhook.go#L92) function are working as expected. Therefore, the tests can be rewritten in unit tests calling those related functions directly and saving the time of setting up the integration tests environments.
