### ISSUE TITLE
Watching clusterAdmissionPolicies changes using `kubectl -w` continuously prints all objects

### ISSUE THREAD

**Issue by mpepping** [kubewarden/kubewarden-controller#612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running `kubectl get clusteradmissionpolicies.policies.kubewarden.io  -w` prints a continuous loop of clusteradmissionpolicies objects, independent of any changes.

### Expected Behavior

I expect the `kubectl get clusteradmissionpolicies.policies.kubewarden.io  -w` command to print the current list of clusteradmissionpolicies objects, then tail/watch for any changes. Like `kubectl get pods -A -w`.

### Steps To Reproduce

1. Run `kubectl get clusteradmissionpolicies.policies.kubewarden.io  -w`
2. Watch the list of clusterAdmissionPolicies continuously scroll by
3. Hit CTRL-C once you've seen enough

### Environment

```markdown
- OS: Linux 
- Architecture: adm64
- Kubernetes: v1.26
- Kubewarden helm-app version: 1.8.0
```

**Comment by viccuad** [comment]
Hi, thanks for reporting this.
Unfortunately I can't reproduce here, my command correctly watches for changes.

What version of `kwctl` are you using and against what Kubernetes version?
Here for example the following works:
```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.3", GitCommit:"a8a1abc25cad87333840cd7d54be2efaf31a3177", GitTreeState:"clean", BuildDate:"2023-10-18T11:33:18Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mpepping** [comment]
Thanks for the reply, @viccuad! The moment you mentioned you could not reproduce the issue, I couldn't either. Until the following situation; 

I applied ~40 clusterAdmissionPolicies to an 'empty' policy-server and use `kubectl get clusteradmissionpolicies.policies.kubewarden.io  -w` to check if the status changes from `pending` to `active`. This usually takses less than a minute. The moment the status changes to `active` the watch command continues with tailing output. Currently for well over 10m. 

If I stop/start the kubectl command, the scrolling continues. 

It does stop over time, apparently. I'm tailing that for a bit now to see how long that will take.

So, I'm afraid this does not make it more clear :) .. but I'm curious if you can reproduce this via the same steps.

```
❯ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.8", GitCommit:"395f0a2fdc940aeb9ab88849e8fa4321decbf6e1", GitTreeState:"clean", BuildDate:"2023-08-24T00:43:07Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mpepping** [comment]
> It does stop over time, apparently. I'm tailing that for a bit now to see how long that will take.

It stopped tailing after 73 minutes (value in the last column). I'll test with a smaller set of policies. Currently deploying ~45 policies.

**Comment by viccuad** [comment]
> It stopped tailing after 73 minutes (value in the last column)

I suppose that's the client-go connection from kubectl, timing out after inactivity, which is expected.

The `kubectl get -w` works by watching for changes in the resource. It doesn't matter if it's Pods or a CRD in our case. The Kubewarden controller changes the status (e.g: from pending to active) when the policy is ready, and that's shown by the Kubernetes api, so I'm not sure there's more we can do in our side. Maybe this issue is a question for the `kubectl` maintainers, to allow for the `kubectl get -w` to not timeout.

May I ask what is your exact purpose?

If it is just to have a list of the policies, and see if they are all ready, you can just look at the readiness probe of the policy-server pod. Or more succintly, wait for the policy-server Deployment to be ready after the rollout when changing the policies.

If it is just to see the list of policies in general, maybe this would suffice:
 `watch -n 1 kubectl get  clusteradmissionpolicies.policies.kubewarden.io` . One can add greps afterwards to filter for pending or active ones for example.

**Comment by mpepping** [comment]
> May I ask what is your exact purpose?

Solely expecting different behaviour than seen. I'd expect one single update per policy (pending > active), as  `kubectl get [..] -w` for other resources do. 

So, not critical, just an annoyance.
