### ISSUE TITLE
Webhook inconsistencies when deleting a policy

### ISSUE THREAD

**Issue by brunorene** [kubewarden/kubewarden-controller#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In my case if I delete a specific policy and/or its policy server I get the error 

```
Error from server (InternalError): Internal error occurred: failed calling webhook "clusterwide-run-as-non-root.kubewarden.admission": failed to call webhook: Post "https://policy-server-default.kubewarden.svc:8443/validate/clusterwide-run-as-non-root?timeout=10s": service "policy-server-default" not found
```

If I add the policy server again (it is always the `default` server) I get 

```
Error from server (InternalError): Internal error occurred: failed calling webhook "clusterwide-run-as-non-root.kubewarden.admission": failed to call webhook: the server could not find the requested resource
```

I am only able to stop the errors by adding the policy again. Any other policy works ok

### Expected Behavior

I should be able to delete a policy or policy server and not affect the apply of resources after that.

### Steps To Reproduce

delete policy or delete policy server

### Environment

```markdown
- OS: Linux
- Architecture: amd64
```

**Comment by jvanz** [comment]
@brunorene I'm working on that and trying to simulate the issue here. But I still failed on that. While I'm trying, can you send the logs of the controller when you delete the policy/policy server ? I would like to see if I can see some messages that I'm reading in the source code. 

Furthermore, I have some questions to clarify some topics that are not clear to me after reading the issue and your messages in the project slack channel. Which will help me to understand what's going on in the reconciliation loop.

- When you said "delete policy server", are you refering to the policy server pods or the policy server definition?
- When you say "I delete a specific policy and/or its policy server I get the error", do you delete the policy and the policy server in isolation or both at the "same time" (one command following the other)?

**Comment by jvanz** [comment]
More questions... Considering the first error message:
```
Error from server (InternalError): Internal error occurred: failed calling webhook "clusterwide-run-as-non-root.kubewarden.admission": failed to call webhook: Post "https://policy-server-default.kubewarden.svc:8443/validate/clusterwide-run-as-non-root?timeout=10s": service "policy-server-default" not found
```

With no surprise, the only way that I could get a similar error, is by deleting the policy server service only. This will not remove the webhook and the policy server pod. I think this is a point of improvement. Our controller could monitor the policy server service and restore it in case of the deletion. Because of that, can you check if this is the case for you? In other words, when you face this error, the webhook is there but the policy server service is gone? 

For the second error:

```
Error from server (InternalError): Internal error occurred: failed calling webhook "clusterwide-run-as-non-root.kubewarden.admission": failed to call webhook: the server could not find the requested resource
```

Can you share the webhook configuration for the `run-as-non-root` policy webhook? I think you can get that with the following command:

```
 kubectl get mutatingwebhookconfigurations clusterwide-run-as-non-root -o yaml
```

Also check if the service pointed in the webhook configuration is running. I would like to know if the webhook is pointing to the wrong service.

**Comment by brunorene** [comment]
Hey hey. So answering the first questions. 

1. Deleting the policy server means: `kubectl delete policyserver default`
2. Deleting the policy means: `kubectl delete clusteradmissionpolicy run-as-non-root`

**Comment by flavio** [comment]
@brunorene this is part of 1.11-RC1
