### ISSUE TITLE
INFO is getting logged on stderr

### ISSUE THREAD

**Issue by pandvag** [kubewarden/kubewarden-controller#693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Log-Level INFO is getting logged on `stderr `instead of `stdout`.
No possibility to prevent info messages in log-output, for instance like `metadata.template.spec.containers.env` within policy-server
`KUBEWARDEN_LOG_LEVEL`

### Expected Behavior

`KUBEWARDEN_LOG_LEVEL` is globally applied for kubewarden-controller & policy-server or a possibility, to explicit set the log-level within each deployment

### Environment

```markdown
aks Kubernetes v1.28.5
kubewarden-controller v1.10.0
helm v2.0.8
```

**Comment by flavio** [comment]
If I understand correctly there are two topics conflated with this issue:

* INFO logs are sent to stderr instead of stdout. Is this happening with policy-server or kubewarden-controller?
* Setting the log level: each policy server can already have its own dedicated log level. This can be set via an environment variable on the `PolicyServer` CRD. We should not force the kubewarden-controller to have the same log level as Policy Server

@pandvag can you please provide some clarification?

**Comment by pandvag** [comment]
Hi @flavio,
it happens with kubewarden-controller v1.10.0. I could find the log-level VAR for policy-server, but not for kubewarden-controller in the helm-chart description. I will try to use `KUBEWARDEN_LOG_LEVEL` for kubewarden-controller as well.

**Comment by flavio** [comment]
We can solve this by updating the helm chart that installs the kubewarden-controller.


Acceptance criteria:
- [ ] The helm chart should provide a way to configure the log level used by the controller.
