### ISSUE TITLE
Reconciliation error: failed to delete PodDisruptionBudget

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kubewarden-controller#707]
[E2E tests](https://github.com/kubewarden/kubewarden-controller/actions/runs/8568790094/job/23483415641) fail with following error:

```bash
~ k logs -n kubewarden kubewarden-controller-6874477666-bqhxz
ERROR	Reconciler error	
{
"controller":"policyserver",
"controllerGroup":"policies.kubewarden.io",
"controllerKind":"PolicyServer",
"PolicyServer":{
"name":"default"
},
"namespace":"",
"name":"default",
"reconcileID":"2dbf5074-0c86-4936-8b93-c23b1cfea9b2",
"error":"reconciliation error: failed to delete PodDisruptionBudget\npoddisruptionbudgets.policy \"policy-server-default\" is forbidden: User \"system:serviceaccount:kubewarden:kubewarden-controller\" cannot delete resource \"poddisruptionbudgets\" in API group \"policy\" in the namespace \"kubewarden\""
}
```

To reproduce it's required use `latest` images for controller & policy server.

**Comment by jvanz** [comment]
As far as I can see, the tests are failing because it use running the `latest` container image which run the controller in a version that requires access to the PDBs but the [helm charts changes](https://github.com/kubewarden/helm-charts/pull/414) to give permissions to that resources is not released yet. Therefore, I see 3 options:

- Wait for a release with the RBAC changes
- Do not use latest images
- Use helm charts from the main branch

**Comment by jvanz** [comment]
During a team call, we decided to wait for the next rc release. Moving to block until we ensure that tests will pass with the latest Helm charts.

**Comment by jvanz** [comment]
The helm charts release candidate with the RBAC changes required is released. I've ran the basic e2e tests locally in my machine. They are green. I'm closing this issue.
