### ISSUE TITLE
Global Taints, Tolerations, Affinity, and Anti-affinity Settings for Kubewarden Stack

### ISSUE THREAD

**Issue by ksathe893** [kubewarden/kubewarden-controller#756]
### Is your feature request related to a problem?

Yes, currently, it is not possible to configure global taints, tolerations, affinity, and anti-affinity settings for all components within the Kubewarden stack using the kubewarden helmchart. This makes it challenging to apply consistent scheduling constraints across the entire stack.the Kubewarden helmchart does not allow you to configure global taints, tolerations, affinity, and anti-affinity settings for all components within the Kubewarden stack

### Solution you'd like

I would like to propose adding support for configuring global taints, tolerations, affinity, and anti-affinity settings in the Kubewarden stack (helmchart - values.yaml). This would enable administrators to define these settings once for the entire stack, rather than having to specify them individually for each component. This feature would enhance flexibility and simplify management of Kubewarden deployments in Kubernetes clusters.

### Alternatives you've considered

- Editing the helm chart (per component) with the required settings.
- Patching the deployment for each component with required settings.

**Comment by flavio** [comment]
Not yet in a workable state, I want to figure out if there are some common patterns about how to manage that inside of helm charts

**Comment by flavio** [comment]
I've asked/looked around. We could do something like Bitnami does:

> In Bitnami they standardized it with `podAffinityPreset` and `podAntiAffinityPreset` to simplify the configurations to the end user, leaving the "advanced" configuration with the options `affinity.podAffinity`, `affinity.nodeAffinity` and `tolerations`. Those options are supported for all Bitnami charts, because they invested the time into standardizing it.

You can see this [here](https://github.com/bitnami/charts/blob/155d842a9517619077f82e2589d0104027a4a004/bitnami/redis/values.yaml#L370-L381) for example

**Comment by flavio** [comment]
To whoever takes this card, please make a concrete example about how the helm chart is going to be changed before starting to work on that.

**Comment by jvanz** [comment]
We have three components where we can define affinity and tolerations: controller deployment, audit scanner job and policy server (considering the recent changes in the CRDs).
The controller and audit-scanner use the same [configuration](https://github.com/kubewarden/helm-charts/blob/76dd5ccad7b11a4346ab8fa58371f8f259511636/charts/kubewarden-controller/values.yaml#L114-L115). The policy server has [affinity](https://github.com/kubewarden/helm-charts/blob/76dd5ccad7b11a4346ab8fa58371f8f259511636/charts/kubewarden-defaults/values.yaml#L117), and tolerations addition is a work in progress. 

I think we can have two new fields in the  `global` [common value](https://github.com/kubewarden/helm-charts/blob/main/common-values.yaml) fields in our helm charts: `affinity` and `tolerations` . If the individual configuration for each component is defined, use it. Otherwise, fallback to the global values. If the global values is not defined do not configure these fields in the resources. 

I have a question for the rest of the @kubewarden/kubewarden-developers, do you want to split the affinity and tolerations used by the controller and audit scanner? In other words, should we have a dedicated configuration for the audit scanner only?

**Comment by viccuad** [comment]
> I think we can have two new fields in the global [common value](https://github.com/kubewarden/helm-charts/blob/main/common-values.yaml) fields in our helm charts: affinity and tolerations . If the individual configuration for each component is defined, use it. Otherwise, fallback to the global values. If the global values is not defined do not configure these fields in the resources.

That sounds fine. Have you thought about providing presets ala bitnami in addition, as suggested in https://github.com/kubewarden/kubewarden-controller/issues/756#issuecomment-2165513038?

> do you want to split the affinity and tolerations used by the controller and audit scanner? In other words, should we have a dedicated configuration for the audit scanner?

I'm ok with it applying to both, that way the Kubewarden stack would be "schedulable" as a block.

Just realized that currently the affinity and tolerations for the audit scanner are taken from `values.affinity`, etc. (see [here](https://github.com/kubewarden/helm-charts/blob/main/charts/kubewarden-controller/templates/audit-scanner.yaml#L56-L62)).

Using `values.affinity`, etc, is fine, but the order in values.yaml should be changed so it is obvious that it applies to both.

**Comment by flavio** [comment]
> I think we can have two new fields in the global [common value](https://github.com/kubewarden/helm-charts/blob/main/common-values.yaml) fields in our helm charts: affinity and tolerations . If the individual configuration for each component is defined, use it. Otherwise, fallback to the global values. If the global values is not defined do not configure these fields in the resources.

This looks like quite some complexity being added into the final chart.

Can you take a closer look at the bitnami example? I wonder if they provide the ability to set only the "global" values.

**Comment by jvanz** [comment]
Bitnami allow users to define affinity in [two](https://github.com/bitnami/charts/blob/0e677c4218a009eb305b0126fad1eb8d0a75229c/bitnami/parse/templates/server-deployment.yaml#L33-L40) ways. When using fields like ``podAffinityPreset`` and `podAntiAffinityPreset` they use some [tpl script](https://github.com/bitnami/charts/blob/0e677c4218a009eb305b0126fad1eb8d0a75229c/bitnami/common/templates/_affinities.tpl#L129-L139) (template) which builds the definition for the user. Or the users can define the [affinity](https://github.com/bitnami/charts/blob/155d842a9517619077f82e2589d0104027a4a004/bitnami/redis/values.yaml#L399) theirselves. And these options are defined inside the component configuration. For example, [this](https://github.com/bitnami/charts/blob/155d842a9517619077f82e2589d0104027a4a004/bitnami/redis/values.yaml#L849-L878) is the affinity for the Redis replicas and [this](https://github.com/bitnami/charts/blob/155d842a9517619077f82e2589d0104027a4a004/bitnami/redis/values.yaml#L373-L399) is for the Redis master. There is no "global" values. What happens is that they have a common [helm chart library](https://helm.sh/docs/topics/library_charts/) containing the templates and they call this template from different helm chart (like the [redis](https://github.com/bitnami/charts/blob/0e677c4218a009eb305b0126fad1eb8d0a75229c/bitnami/redis/Chart.yaml#L20-L25) one).  I think using a helm chart library  is a overkill for us. Furthermore, our users are used to define the affinity in the values files and I can add a fallback to a "global" values using the default function. I'll open a draft PR to show what I have in mind.

**Comment by viccuad** [comment]
I'm ok with providing the `.values.global.affinity`, `.values.global.antiaffinity` and `.values.global.tolerations`, `.values.global.taints`, etc. There will be repetition of their example values between kubewarden-controller and kubewarden-defaults.

I am happy not adding `podAffinityPreset` et al for now.

**Comment by flavio** [comment]
@jose I'm fine with the approach you propose. I propose to leave one single way to define all these configuration: via the `.values.global.{*}`. This would be a breaking change of the helm charts that we must document.

I propose to come up with a small example of the `values.yml` used to deploy the `kubewarden-controller`  and the `kubewarden-defaults` helm charts so that @ksathe893 can provide his feedback
