### ISSUE TITLE
Spike: about how to convert all weaveworks Rego policies

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#766]
Spike: about how to convert all [these policies](https://github.com/weaveworks/policy-library) to Kubewarden

Define:
* repo structure
* what the tool should be doing

**Comment by viccuad** [comment]
Weaveworks uses the docker image `weaveworks/polctl` for automation on
auto-generating, testing, documenting, and releasing the policies. Sadly, I
couldn't find the docker image anywhere, and the repo
https://github.com/weaveworks/polctl has been deleted.

The repo uses `openpolicyagent/opa` to test the policies. Since we use `opa` to
build as a wasm target, I find it a good compromise to keep that workflow.

Weavework policies are marked with `spec.standards`. The list of available
standards are in `./standards`
([example](https://github.com/search?q=repo%3Aweaveworks%2Fpolicy-library%20weave.controls.cis-benchmark.5.7.4&type=code)),
and the policies have `spec.standards`. For now, transform these into
`metadata.annotations`.

The policies are Rego OPA policies.

### Acceptance criteria

The end result is a monorepo with the following format:

```
$ tree
.
├── LICENSE
├── artifacthub-repo.yml
├── policy1/
│   └── 0.1.0/
│       ├── README.md
│       ├── tests/
|       │   └── deployment.yaml
│       ├── policy.rego
│       ├── Makefile
│       ├── metadata.yml
│       └── artifacthub-pkg.yml
└── policy2/
    ...
```

For that:

- [ ] Per policy in `examples/,policies/`, do a 1-time conversion:

  - [ ] Reuse our OPA Rego `Makefile` from [disallow-service-loadbalander-policy](https://github.com/kubewarden/disallow-service-loadbalancer-policy). Should be
        adapted to run rego tests with `opa` from `./tests`. Not all policies have a
        `./tests/policy_test.rego`.
  - [ ] Compile a `README.md` from `policy.yaml`, by reusing the following fields in a template:
    - [ ] `metadata.name` with `weave.policies` prefix removed.
    - [ ] `spec.name`, `description`, `how_to_solve`, `tags`.
  - [ ] Compile a `metadata.yml` from `policy.yaml`, by reusing the following fields from the Weaveworks policy:

          - `spec.id`, without the prefix `weave.policies`, as annotations
            `io.kubewarden.policy.title`, `io.kubewarden.policy.ociUrl:

    ghcr.io/kubewarden/policies/<id>`, `io.kubewarden.policy.url:
    https://github.com/kubewarden/<id>`.

          - `io.kubewarden.policy.url` and `io.kubewarden.policy.source` hardcoded to the Rego monorepo for these policies. (e.g: `https://github.com/kubewarden/rego-policies`).

          - `spec.category` as annotations `io.kubewarden.policy.category`, without prefix `weave.category`.
          - `spec.severity` as annotations `io.kubewarden.policy.severity`
          - `spec.standards` as annotation `io.kubewarden.policy.standards`, where each
            element in the `controls` array is a new annotation, and it is commented until we evaluate further. The list of available

    standards are in `./standards` ([example](https://github.com/search?q=repo%3Aweaveworks%2Fpolicy-library%20weave.controls.cis-benchmark.5.7.4&type=code)).

          - `spec.description` as annotation `io.kubewarden.policy.description`
          - `spec.targets` into `rules` and the annotation `io.artifacthub.resources` by computing the list of resources.

  - [ ] Adapt the `policy.rego`:
    - Use the same `package` for all rego files, including tests (e.g: `package policy`).
  - [ ] Reuse `./tests/`, which will get run by the `make tests`
  - `artifacthub-pkg.yml` following [artifacthub docs](https://artifacthub.io/docs/topics/repositories/kubewarden-policies/).

- Weavework policies are marked with `spec.standards`. The list of available
  standards are in `./standards` ([example](https://github.com/search?q=repo%3Aweaveworks%2Fpolicy-library%20weave.controls.cis-benchmark.5.7.4&type=code)).
- Manually mark the converted policies with annotation
  `io.kubewarden.policy.category: Best practices RBAC` for those policies listed in
  from `./goodpractices`.
- CI & CD: I found no way to programatically create jobs. Hence the jobs will go through all repos when they are called.
  To release, for each policy folder, if no git tag matching the policy id and version, build and push the annotated-policy.wasm as usual.

### Unresolved

- Weaveworks' repo license. We should fork and conserve git history.
- Evaluate the `spec.standards`. For these to be valid, the data structure of the k8s deployment needs to match the expected. (E.g: expecting users to deploy things segregated by namespaces, and is a specific way).

**Comment by jvanz** [comment]
The proposed initial approach looks fine to me. I think we can start writing a script to perform some of this migration and see what happens.

**Comment by flavio** [comment]
Sounds good to me. I think we can move forward and start 2 spikes:

1. Create the migration script. Focus on policies that have unit tests so far
2. Create the monorepo structure, populate it with the script. See how it scales

**Comment by fabriziosestito** [comment]
Spike completed.

The output has been tracked by the issues:
https://github.com/kubewarden/kubewarden-controller/issues/805
https://github.com/kubewarden/kubewarden-controller/issues/806
