### ISSUE TITLE
Validate PolicyGroup members name

### ISSUE THREAD

**Issue by fabriziosestito** [kubewarden/kubewarden-controller#876]
### Is your feature request related to a problem?

Policy group members will be bound to functions with the same name when evaluating a CEL expression. Therefore, policy member's names should follow the same validation rules as CEL names.

### Solution you'd like

Add a validation step to validate policy member names.

**Comment by fabriziosestito** [comment]
@jvanz this could be helpful: https://github.com/kubewarden/cel-policy/pull/83#discussion_r1751393241

**Comment by jvanz** [comment]
> [@jvanz](https://github.com/jvanz) this could be helpful: [kubewarden/cel-policy#83 (comment)](https://github.com/kubewarden/cel-policy/pull/83#discussion_r1751393241)

Thanks! I was reading the code. It's a good starting point. However, I think we cannot use that regex because it's meant to [escape the CEL expressions](https://github.com/kubernetes/apiserver/blob/14b3ab9aa060d9d0a8151a7f2bbd03e13465a1e7/pkg/cel/escaping.go#L100-L136), not to check if it's a valid identifier. For example, that regex is used to identify the dot in expressions like [a.b](https://github.com/kubernetes/apiserver/blob/14b3ab9aa060d9d0a8151a7f2bbd03e13465a1e7/pkg/cel/escaping_test.go#L36). Therefore, if we use it, we will allow policy names with dots, which is not supported. Consequently, I've written another regex based on the [policy definition](https://github.com/google/cel-spec/blob/master/doc/langdef.md#syntax). Additionally, I've decided to use a set to store the keywords reserved by the CEL policy because it matches the policy syntax.
